### ISSUE TITLE
这个是怎么回事

### ISSUE THREAD

**Issue by lionche** [HarborZeng/NwuGradeTeller#1]
HTTP Status 500 – Internal Server Error
Type Exception Report

Message 无法访问位于以下位置的 WSDL: http://219.245.18.61:81/KEY/MURPNewsService.asmx?WSDL。该操作失败并显示:

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.xml.ws.WebServiceException: 无法访问位于以下位置的 WSDL: http://219.245.18.61:81/KEY/MURPNewsService.asmx?WSDL。该操作失败并显示: 
	Server returned HTTP response code: 503 for URL: http://219.245.18.61:81/KEY/MURPNewsService.asmx?WSDL。
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(RuntimeWSDLParser.java:250)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:231)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:194)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:163)
	com.sun.xml.internal.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:348)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:306)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:215)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:196)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:192)
	com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:104)
	javax.xml.ws.Service.<init>(Service.java:77)
	cn.tellyouwhat.gradeteller.murpnewsservice.MURPNewsService.<init>(MURPNewsService.java:42)
	cn.tellyouwhat.gradeteller.servlet.QueryGradeServlet.doPost(QueryGradeServlet.java:33)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cn.tellyouwhat.gradeteller.filter.EncodeFilter.doFilter(EncodeFilter.java:15)
Root Cause

java.io.IOException: Server returned HTTP response code: 503 for URL: http://219.245.18.61:81/KEY/MURPNewsService.asmx?WSDL
	sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	java.net.URL.openStream(URL.java:1045)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.createReader(RuntimeWSDLParser.java:984)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.resolveWSDL(RuntimeWSDLParser.java:385)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:216)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:194)
	com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:163)
	com.sun.xml.internal.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:348)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:306)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:215)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:196)
	com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:192)
	com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:104)
	javax.xml.ws.Service.<init>(Service.java:77)
	cn.tellyouwhat.gradeteller.murpnewsservice.MURPNewsService.<init>(MURPNewsService.java:42)
	cn.tellyouwhat.gradeteller.servlet.QueryGradeServlet.doPost(QueryGradeServlet.java:33)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cn.tellyouwhat.gradeteller.filter.EncodeFilter.doFilter(EncodeFilter.java:15)
Note The full stack trace of the root cause is available in the server logs.

**Comment by HarborZeng** [comment]
我去今天才看到你的ISSUE，学校已经关了这个查成绩的通道，再也没有办法了
